name: Build and Release XBattWatch

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Trigger on tags starting with "v"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build resources
        run: windres resources/resources.rc -O coff -o resources.res

      - name: Build executable
        run: g++ -o XBattWatch src/main.cpp resources.res -DUNICODE -D_UNICODE -lXinput -mwindows -s

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: XBattWatch.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
